# Generated by Django 5.2.8 on 2025-11-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('accessories', 'Accessories'), ('kids', 'Kids'), ('others', 'Others')], default='others', max_length=20),
        ),
    ]
