# Generated by Django 5.2.8 on 2025-11-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('accessories', 'Accessories'), ('kids', 'Kids'), ('grocery', 'Grocery'), ('electronics', 'Electronics'), ('others', 'Others')], default='others', max_length=20),
        ),
    ]
